In [6]:
import numpy as np
from sympy import Matrix

In [1]:
s = int(input('s='))
g = int(input('g='))
p = 2 * (s+g)
m = -1*p + s

s=12
g=3


In [11]:
A = np.array(
    [[p, m, 2*s],
     [m, 2*p + s, m],
     [2*s, m, p]]
) / 6
print(f'Матрица А\n{A}')

Матрица А
[[ 5. -3.  4.]
 [-3. 12. -3.]
 [ 4. -3.  5.]]


In [37]:
from scipy.linalg import fractional_matrix_power, logm, cosm
from numpy.linalg import matrix_power

# Функция от матрицы A
def f(A):
    return fractional_matrix_power(A, 3/5) + logm(matrix_power(A, 2) + matrix_power(cosm(A), 2))

print(f'Функция от матрицы А\n{f(A)}')

Функция от матрицы А
[[ 4.55709093 -1.31908562  3.30095635]
 [-1.31908562  9.17713289 -1.31908562]
 [ 3.30095635 -1.31908562  4.55709093]]


In [38]:
T, J = Matrix(A).jordan_form()
display(T, J)

Matrix([
[-1.0, 1.0,  1.0],
[   0, 1.0, -2.0],
[ 1.0, 1.0,  1.0]])

Matrix([
[1.0,   0,    0],
[  0, 6.0,    0],
[  0,   0, 15.0]])

Матрица собственных векторов T
Matrix([[-1.00000000000000, 1.00000000000000, 1.00000000000000], [0, 1.00000000000000, -2.00000000000000], [1.00000000000000, 1.00000000000000, 1.00000000000000]])


In [39]:
J_, T_ = np.array(J, dtype='float64'), np.array(T, dtype='float64')
print(f'Матрица собственных векторов T\n{T_}')
print(f'Матрица Жордана J\n{J_}')

Матрица собственных векторов T
[[-1.  1.  1.]
 [ 0.  1. -2.]
 [ 1.  1.  1.]]
Матрица Жордана J
[[ 1.  0.  0.]
 [ 0.  6.  0.]
 [ 0.  0. 15.]]


In [41]:
fa = T_@f(J_)@np.linalg.inv(T_)
print(f'Функция от матрицы А\n{fa}')

Функция от матрицы А
[[ 4.55709093 -1.31908562  3.30095635]
 [-1.31908562  9.17713289 -1.31908562]
 [ 3.30095635 -1.31908562  4.55709093]]
