In [73]:
import numpy as np
from scipy.linalg import expm
np.set_printoptions(precision=3, suppress=True)

g = 3
s = 12
n = 8
nt = 10
m = n-1
alpha = 1
h = 1/n
tau = 1.5/nt
c = alpha / h**2
E = np.eye(m)
a1 = np.ones((m-1,))
A = -2*E + np.diag(a1,1) + np.diag(a1,-1)
A = c*A
print('Матрица А\n', A)

F = np.zeros((m, 1))
F[0] = g
F[m-1] = s
F = c*F
res = np.empty((nt, n+1))
res[:nt, 0] = g
res[:nt, n] = s
print(res)

x = np.arange(0, 1, h)
psi = g + (g+3*s)*x[1:] - 2*(g+s)*x[1:]**2
J, T = np.linalg.eig(A)
print('Матрица собственных векторов\n',T)
print('Собственные значения\n', J)

T_inv = np.linalg.inv(T)
print('Матрица обратная к матрице Т\n', T_inv)
t_res = []
for k in range(nt):
    t = tau*k
    ETJ = np.exp(t*J)
    EAt = T@ETJ@T_inv
    u = EAt@psi - np.linalg.inv(A)@(E-EAt)@F
    res[k,1:-1] = u[:][0]
    t_res.append(t)
print('Массив координат точек табуляции по времени\n', t_res)
print('Массив значений температуры в точках табуляции\n', res)

Матрица А
 [[-128.   64.    0.    0.    0.    0.    0.]
 [  64. -128.   64.    0.    0.    0.    0.]
 [   0.   64. -128.   64.    0.    0.    0.]
 [   0.    0.   64. -128.   64.    0.    0.]
 [   0.    0.    0.   64. -128.   64.    0.]
 [   0.    0.    0.    0.   64. -128.   64.]
 [   0.    0.    0.    0.    0.   64. -128.]]
[[ 3.    31.104 31.104 31.104 31.104 31.104 31.104 31.104 12.   ]
 [ 3.    11.378 11.378 11.378 11.378 11.378 11.378 11.378 12.   ]
 [ 3.     5.805  5.805  5.805  5.805  5.805  5.805  5.805 12.   ]
 [ 3.     4.514  4.514  4.514  4.514  4.514  4.514  4.514 12.   ]
 [ 3.     4.215  4.215  4.215  4.215  4.215  4.215  4.215 12.   ]
 [ 3.     4.146  4.146  4.146  4.146  4.146  4.146  4.146 12.   ]
 [ 3.     4.13   4.13   4.13   4.13   4.13   4.13   4.13  12.   ]
 [ 3.     4.126  4.126  4.126  4.126  4.126  4.126  4.126 12.   ]
 [ 3.     4.125  4.125  4.125  4.125  4.125  4.125  4.125 12.   ]
 [ 3.     4.125  4.125  4.125  4.125  4.125  4.125  4.125 12.   ]]
Матрица собс